// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs pdf-split`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "pdf-merge",
    "icon": "📑",
    "name": {
      "en": "Merge PDF",
      "ja": "PDFを結合",
      "zh": "合并 PDF",
      "de": "PDF zusammenführen",
      "es": "Unir PDF"
    },
    "desc": {
      "en": "Combine several PDFs into one.",
      "ja": "複数のPDFを1つにまとめます。",
      "zh": "把多个 PDF 合成一个。",
      "de": "Mehrere PDFs zu einem zusammenfügen.",
      "es": "Combina varios PDF en uno solo."
    }
  },
  {
    "slug": "pdf-to-image",
    "icon": "📸",
    "name": {
      "en": "PDF to Image",
      "ja": "PDFを画像に変換",
      "zh": "PDF 转图片",
      "de": "PDF in Bild",
      "es": "PDF a imagen"
    },
    "desc": {
      "en": "Render PDF pages to PNG or JPG.",
      "ja": "PDFの各ページをPNGまたはJPGに変換します。",
      "zh": "把 PDF 页面渲染成 PNG 或 JPG。",
      "de": "PDF-Seiten als PNG oder JPG rendern.",
      "es": "Convierte páginas de PDF a PNG o JPG."
    }
  },
  {
    "slug": "pdf-extract-text",
    "icon": "📝",
    "name": {
      "en": "Extract PDF Text",
      "ja": "PDFのテキストを抽出",
      "zh": "提取 PDF 文本",
      "de": "PDF-Text extrahieren",
      "es": "Extraer texto de PDF"
    },
    "desc": {
      "en": "Pull the text out of a PDF into a .txt file.",
      "ja": "PDFのページからテキストを抽出してテキストファイルに。",
      "zh": "把 PDF 中的文本提取为文本文件。",
      "de": "Text aus einem PDF in eine .txt-Datei holen.",
      "es": "Saca el texto de un PDF a un archivo .txt."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'pdf-split';
